language: node_js
node_js:
- node
branches:
  only:
  - master
before_script:
- yarn global add polymer-cli bower semver
- yarn install
script:
- cd $TRAVIS_BUILD_DIR/build
- if [ $TRAVIS_EVENT_TYPE = "cron" -o $TRAVIS_EVENT_TYPE = "api" ]; then ./run.sh; fi
- if [ $TRAVIS_EVENT_TYPE = "cron" -o $TRAVIS_EVENT_TYPE = "api" ]; then ./push.sh; fi
